/** Supabase `catalog_entries.collection` keys for static lib/data.ts content. */
export const CATALOG_COLLECTIONS = {
  services: "services",
  visas: "visas",
  visaCountries: "visa_countries",
  cheapRoutes: "cheap_routes",
  usaRoutes: "usa_routes",
  flights: "flights",
  stays: "stays",
  cars: "cars",
  cruises: "cruises",
  tours: "tours",
  tickets: "tickets",
  properties: "properties",
  agents: "agents",
  agencies: "agencies",
  packages: "packages",
  destinations: "destinations",
  reviews: "reviews",
  referralTiers: "referral_tiers",
  trustItems: "trust_items",
  stats: "stats",
  roles: "roles",
  faqs: "faqs",
  travelGuides: "travel_guides",
  visaHubCards: "visa_hub_cards",
  ticketRoutes: "ticket_routes",
  propertyListings: "property_listings",
  marketplaceProviders: "marketplace_providers",
  aiPrompts: "ai_prompts",
  siteConstants: "site_constants",
} as const;

export type CatalogCollectionKey = (typeof CATALOG_COLLECTIONS)[keyof typeof CATALOG_COLLECTIONS];
