import type { SeoPageConfig } from "@/components/SeoLandingPage";

const DISCLAIMER =
  "Globe Travel Voyage is not a government agency, embassy, or immigration lawyer. Visa approval is never guaranteed.";

const BASE_FAQ = [
  {
    q: "Does Globe Travel Voyage guarantee visa approval?",
    a: "No. Embassies and consulates make all visa decisions. We offer preparation support and document review only.",
  },
  {
    q: "What free tools are available?",
    a: "Free account, visa country guides, basic checklist, browse providers, and request quotes at no platform fee.",
  },
];

export const SEO_VISA_PAGES: Record<string, SeoPageConfig> = {
  "usa-from-pakistan": {
    eyebrow: "🇵🇰 → 🇺🇸 Visa guide",
    title: "USA visa from Pakistan",
    subtitle: `Step-by-step guidance for Pakistani applicants. ${DISCLAIMER}`,
    breadcrumbs: [{ label: "Home", href: "/" }, { label: "Visa", href: "/visa" }, { label: "USA from Pakistan" }],
    highlights: [
      { label: "Typical processing", value: "3–12 weeks" },
      { label: "Consular fee", value: "From $185" },
      { label: "Document review", value: "From $49" },
      { label: "Support", value: "Dashboard" },
    ],
    steps: [
      { title: "Choose visa type", text: "B1/B2 visitor, F-1 student, or other category based on your purpose." },
      { title: "Complete DS-160", text: "Fill the online form and save your confirmation page." },
      { title: "Pay embassy fees", text: "Pay the MRV fee and schedule biometrics and interview." },
      { title: "Prepare documents", text: "Financial proof, ties to home country, and travel purpose." },
      { title: "Attend interview", text: "Be honest and concise at Islamabad or Karachi." },
      { title: "Track your case", text: "After paid service purchase, track preparation in your dashboard." },
    ],
    faqs: [
      ...BASE_FAQ,
      { q: "Can I get document review before applying?", a: "Yes. Visa Document Review ($49) includes expert review and case tracking." },
    ],
    freeCta: { label: "Free visa checklist", href: "/visa/start" },
    paidCta: { label: "Visa services from $49", href: "/services#premium" },
  },
  "canada-from-india": {
    eyebrow: "🇮🇳 → 🇨🇦 Visa guide",
    title: "Canada visa from India",
    subtitle: `Visitor, study, and work pathways for Indian applicants. ${DISCLAIMER}`,
    breadcrumbs: [{ label: "Home", href: "/" }, { label: "Visa", href: "/visa" }, { label: "Canada from India" }],
    highlights: [
      { label: "Visitor visa", value: "TRV" },
      { label: "Biometrics", value: "Required" },
      { label: "Document review", value: "From $49" },
      { label: "Processing", value: "Varies" },
    ],
    steps: [
      { title: "Determine pathway", text: "Visitor, study permit, or work permit based on your goals." },
      { title: "Gather documents", text: "Passport, financial proof, purpose of visit, and forms." },
      { title: "Apply online", text: "Submit through the official IRCC portal." },
      { title: "Biometrics", text: "Complete biometrics at a VAC if required." },
      { title: "Track application", text: "Monitor status through official channels." },
      { title: "Get expert help", text: "Upgrade to paid preparation support when needed." },
    ],
    faqs: BASE_FAQ,
    freeCta: { label: "Free visa checklist", href: "/visa/start" },
    paidCta: { label: "Visa Application Assistance — $99", href: "/services#premium" },
  },
  "uk-from-uae": {
    eyebrow: "🇦🇪 → 🇬🇧 Visa guide",
    title: "UK visa from UAE",
    subtitle: `Standard Visitor and other UK routes for UAE residents. ${DISCLAIMER}`,
    breadcrumbs: [{ label: "Home", href: "/" }, { label: "Visa", href: "/visa" }, { label: "UK from UAE" }],
    highlights: [
      { label: "Common visa", value: "Standard Visitor" },
      { label: "Application", value: "Online" },
      { label: "Document review", value: "From $49" },
      { label: "Decision", value: "By UKVI" },
    ],
    steps: [
      { title: "Check eligibility", text: "Confirm the right UK visa category for your visit." },
      { title: "Apply online", text: "Complete the application on the official UK site." },
      { title: "Book appointment", text: "Attend a visa application centre in the UAE." },
      { title: "Submit documents", text: "Financial proof, itinerary, and supporting letters." },
      { title: "Await decision", text: "Processing times vary by season and category." },
      { title: "Paid prep support", text: "Optional expert assistance through Globe Travel Voyage." },
    ],
    faqs: BASE_FAQ,
    freeCta: { label: "Free visa checklist", href: "/visa/start" },
    paidCta: { label: "Premium visa support", href: "/services#premium" },
  },
  "schengen-from-pakistan": {
    eyebrow: "🇵🇰 → 🇪🇺 Schengen guide",
    title: "Schengen visa from Pakistan",
    subtitle: `Short-stay Schengen guidance for Pakistani passport holders. ${DISCLAIMER}`,
    breadcrumbs: [{ label: "Home", href: "/" }, { label: "Visa", href: "/visa" }, { label: "Schengen from Pakistan" }],
    highlights: [
      { label: "Stay limit", value: "90/180 days" },
      { label: "Main destination", value: "Apply there" },
      { label: "Document review", value: "From $49" },
      { label: "Insurance", value: "Required" },
    ],
    steps: [
      { title: "Pick main country", text: "Apply at the embassy of your main Schengen destination." },
      { title: "Book appointment", text: "Schedule through the designated visa centre." },
      { title: "Prepare itinerary", text: "Flights, hotels, and travel insurance." },
      { title: "Financial proof", text: "Bank statements and sponsorship if applicable." },
      { title: "Submit application", text: "Attend appointment with complete file." },
      { title: "Case tracking", text: "Paid services include dashboard case tracking." },
    ],
    faqs: BASE_FAQ,
    freeCta: { label: "Free visa checklist", href: "/visa/start" },
    paidCta: { label: "Visa services from $49", href: "/services#premium" },
  },
};

export const SEO_TRAVEL_PAGES: Record<string, SeoPageConfig> = {
  dubai: {
    eyebrow: "✈️ Destination",
    title: "Travel to Dubai",
    subtitle: "Plan your Dubai trip with free AI tools and optional concierge support. Prices and availability can change.",
    breadcrumbs: [{ label: "Home", href: "/" }, { label: "Destinations", href: "/destinations" }, { label: "Dubai" }],
    highlights: [
      { label: "Best for", value: "Luxury & city breaks" },
      { label: "AI planner", value: "Free" },
      { label: "Concierge", value: "From $299" },
      { label: "Providers", value: "Verified listings" },
    ],
    steps: [
      { title: "Plan your dates", text: "Use the free AI trip planner for a day-by-day outline." },
      { title: "Compare stays", text: "Browse hotels and properties from verified hosts." },
      { title: "Book experiences", text: "Request quotes from local guides and agencies." },
      { title: "Visa check", text: "Many nationalities receive visa on arrival — verify officially." },
      { title: "Premium itinerary", text: "Upgrade to Premium AI Trip Plan ($19) for export-ready plans." },
      { title: "Concierge", text: "Luxury Concierge Planning ($299) for complex trips." },
    ],
    faqs: [
      { q: "Are prices guaranteed?", a: "No. Sample estimates on browse pages are for planning only. Confirm with providers before booking." },
      ...BASE_FAQ.slice(1),
    ],
    freeCta: { label: "Free AI trip planner", href: "/trip-planner" },
    paidCta: { label: "Premium trip services", href: "/services#premium" },
  },
  maldives: {
    eyebrow: "🏝️ Destination",
    title: "Travel to the Maldives",
    subtitle: "Honeymoon and luxury island planning. Globe Travel Voyage is not a travel supplier.",
    breadcrumbs: [{ label: "Home", href: "/" }, { label: "Destinations", href: "/destinations" }, { label: "Maldives" }],
    highlights: [
      { label: "Best for", value: "Honeymoons" },
      { label: "Honeymoon plan", value: "$499" },
      { label: "AI planner", value: "Free" },
      { label: "Quotes", value: "Free" },
    ],
    steps: [
      { title: "Pick your atoll", text: "Research resorts and transfer options." },
      { title: "Set budget", text: "Use free tools to outline costs — confirm with agencies." },
      { title: "Request quotes", text: "Contact verified agencies for packages." },
      { title: "Honeymoon upgrade", text: "Honeymoon Planning ($499) for bespoke itineraries." },
      { title: "Save your trip", text: "Bookmark plans in your free dashboard." },
      { title: "Book through providers", text: "Final bookings are with your chosen agency or resort." },
    ],
    faqs: [{ q: "Do you book resorts directly?", a: "We connect you with verified providers. We are not a hotel chain or tour operator." }, ...BASE_FAQ.slice(1)],
    freeCta: { label: "Free trip planner", href: "/trip-planner" },
    paidCta: { label: "Honeymoon Planning — $499", href: "/services#premium" },
  },
  turkey: {
    eyebrow: "🕌 Destination",
    title: "Travel to Turkey",
    subtitle: "Istanbul, Cappadocia, and coast — plan with free tools or human planners.",
    breadcrumbs: [{ label: "Home", href: "/" }, { label: "Destinations", href: "/destinations" }, { label: "Turkey" }],
    highlights: [
      { label: "Highlights", value: "Istanbul · Cappadocia" },
      { label: "Human planner", value: "$99" },
      { label: "Visa guides", value: "Free" },
      { label: "Tours", value: "Marketplace" },
    ],
    steps: [
      { title: "Check visa rules", text: "Use free country guides for your nationality." },
      { title: "Build itinerary", text: "Free AI planner for multi-city routes." },
      { title: "Find guides", text: "Browse verified local tour guides." },
      { title: "Human planner", text: "Human Trip Planner ($99) for custom advice." },
      { title: "Request quotes", text: "Free quote requests to agencies." },
      { title: "Save & track", text: "Dashboard saves trips and messages." },
    ],
    faqs: BASE_FAQ,
    freeCta: { label: "Free AI planner", href: "/trip-planner" },
    paidCta: { label: "Human Trip Planner — $99", href: "/services#premium" },
  },
  saudi: {
    eyebrow: "🕋 Destination",
    title: "Travel to Saudi Arabia",
    subtitle: "Umrah, business, and leisure travel planning. Verify visa rules officially.",
    breadcrumbs: [{ label: "Home", href: "/" }, { label: "Destinations", href: "/destinations" }, { label: "Saudi Arabia" }],
    highlights: [
      { label: "Visa types", value: "Tourism · Umrah · Business" },
      { label: "Checklist", value: "Free" },
      { label: "Agencies", value: "Marketplace" },
      { label: "Support", value: "Dashboard" },
    ],
    steps: [
      { title: "Confirm visa type", text: "Check official requirements for your purpose." },
      { title: "Use free checklist", text: "Document list in your dashboard." },
      { title: "Find agencies", text: "Browse verified travel agencies." },
      { title: "Plan your stay", text: "Hotels and furnished stays on the marketplace." },
      { title: "Paid visa help", text: "Optional document review from $49." },
      { title: "Track in dashboard", text: "Messages and bookings in one place." },
    ],
    faqs: BASE_FAQ,
    freeCta: { label: "Free visa checklist", href: "/visa/start" },
    paidCta: { label: "Visa services", href: "/services#premium" },
  },
  uae: {
    eyebrow: "🇦🇪 Destination",
    title: "Travel to the UAE",
    subtitle: "Dubai, Abu Dhabi, and beyond — free planning tools and verified providers.",
    breadcrumbs: [{ label: "Home", href: "/" }, { label: "Destinations", href: "/destinations" }, { label: "UAE" }],
    highlights: [
      { label: "Cities", value: "Dubai · Abu Dhabi" },
      { label: "AI planner", value: "Free" },
      { label: "Properties", value: "Monthly stays" },
      { label: "Flights", value: "Compare" },
    ],
    steps: [
      { title: "Entry requirements", text: "Many visitors qualify for visa on arrival — verify for your passport." },
      { title: "Plan cities", text: "Free AI itinerary for multi-emirate trips." },
      { title: "Compare flights", text: "Browse routes — prices are estimates until confirmed." },
      { title: "Book stays", text: "Hotels and monthly furnished apartments." },
      { title: "Local tours", text: "Verified guides and experiences." },
      { title: "Concierge", text: "Luxury Concierge Planning ($299) for complex trips." },
    ],
    faqs: BASE_FAQ,
    freeCta: { label: "Free trip planner", href: "/trip-planner" },
    paidCta: { label: "Concierge — $299", href: "/services#premium" },
  },
};
