import type { Metadata } from "next";
import Link from "next/link";
import { PageHeader } from "@/components/PageHeader";

export const metadata: Metadata = {
  title: "Privacy Policy",
  description:
    "Globe Travel Voyage Privacy Policy — how we collect, use and protect your information.",
};

const sections = [
  {
    title: "Information we collect",
    body: "When you use Globe Travel Voyage, we may collect information you provide directly (such as name, email address, and travel preferences), information generated by your use of the platform (such as search queries and pages visited), and technical information (such as IP address, browser type, and device identifiers). Account, request, and payment data are stored securely in Supabase when you register or submit forms.",
  },
  {
    title: "How we use information",
    body: "We use information to operate and improve the platform, personalize your experience, send relevant communications if you opt in, respond to your requests and support queries, and comply with legal obligations. We do not sell your personal information to third parties.",
  },
  {
    title: "Third-party providers",
    body: "When you interact with third-party service providers listed on our marketplace (visa agents, travel agencies, tour guides, property hosts), their own privacy policies apply. We encourage you to review those policies before sharing personal information with any provider.",
  },
  {
    title: "Cookies and tracking",
    body: "We may use cookies and similar tracking technologies to enhance your experience, analyze usage patterns, and deliver relevant content. You can control cookies through your browser settings. Some features of the platform may not function correctly if cookies are disabled.",
  },
  {
    title: "Data security",
    body: "We implement appropriate technical and organizational measures to protect your information. However, no method of transmission over the internet or electronic storage is 100% secure. We cannot guarantee absolute security of your data.",
  },
  {
    title: "Your rights",
    body: "Depending on your location, you may have the right to access, correct, or delete your personal information, object to or restrict certain processing, and withdraw consent at any time. To exercise these rights, please contact us through the contact page.",
  },
  {
    title: "Children",
    body: "Our platform is not directed at children under the age of 16. We do not knowingly collect personal information from children under 16. If you believe a child has provided us with personal information, please contact us.",
  },
  {
    title: "Changes to this policy",
    body: "We may update this Privacy Policy from time to time. When we do, we will update the 'Last updated' date below and, where appropriate, notify you. Your continued use of the platform after changes are posted constitutes acceptance of the updated policy.",
  },
];

export default function PrivacyPage() {
  return (
    <>
      <PageHeader
        eyebrow="Legal"
        title="Privacy Policy"
        subtitle="How Globe Travel Voyage collects, uses and protects your information."
        breadcrumbs={[
          { label: "Home", href: "/" },
          { label: "Legal", href: "/legal/disclaimer" },
          { label: "Privacy Policy" },
        ]}
      />

      <section className="section">
        <div className="container-px max-w-4xl">
          <div className="space-y-8">
            {sections.map((s, i) => (
              <div key={s.title} className="card p-6">
                <h2 className="flex items-center gap-2 text-base font-bold text-navy">
                  <span className="flex h-7 w-7 items-center justify-center rounded-full bg-blue/10 text-xs font-extrabold text-blue">
                    {i + 1}
                  </span>
                  {s.title}
                </h2>
                <p className="mt-3 text-sm leading-relaxed text-navy/70">{s.body}</p>
              </div>
            ))}
          </div>

          <div className="mt-12 border-t border-soft-200 pt-8 text-sm text-navy/55">
            <p>Last updated: June 2025</p>
            <p className="mt-2">
              For privacy questions, please{" "}
              <Link href="/contact" className="font-semibold text-blue underline">
                contact us
              </Link>
              .
            </p>
            <div className="mt-4 flex flex-wrap gap-4">
              <Link href="/legal/disclaimer" className="text-blue hover:underline">
                Disclaimer
              </Link>
              <Link href="/legal/terms" className="text-blue hover:underline">
                Terms of Service
              </Link>
            </div>
          </div>
        </div>
      </section>
    </>
  );
}
